version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 on the host to port 80 on the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
